import { Module } from '@nestjs/common'
import { APP_GUARD } from '@nestjs/core'
import { PrismaService } from '../../../packages/database/src/prisma.service.js'
import { AuthGuard } from '../../../packages/security/src/auth.js'
import { AuthController } from './auth.controller.js'
import { AuthService } from './auth.service.js'
import { ChannelsController } from './channels.controller.js'
import { ChannelsService } from './channels.service.js'
import { ClientController } from './client.controller.js'
import { ModelsController } from './models.controller.js'
import { ModelsService } from './models.service.js'
import { ReportsController } from './reports.controller.js'
import { SkillsController } from './skills.controller.js'
import { UsageController } from './usage.controller.js'
import { GovernanceController } from './governance.controller.js'
import { MonitoringController } from './monitoring.controller.js'
import { ObjectStorageService } from '../../../packages/storage/src/object-storage.js'
import { MetricsController } from '../../../packages/monitoring/src/metrics.controller.js'
import { OrganizationsController } from './organizations.controller.js'
import { AuditInterceptor } from '../../../packages/http/src/audit.interceptor.js'
import { ChannelModelsController } from './channel-models.controller.js'
import { ChannelModelsService } from './channel-models.service.js'
import { ModelTestingService } from './model-testing.service.js'
import { ModelBindingService } from './model-binding.service.js'
import { ModelTestingController } from './model-testing.controller.js'
import { AnalyticsController } from './analytics.controller.js'
import { AnalyticsService } from './analytics.service.js'
import { ProcurementCostsController } from './procurement-costs.controller.js'
import { ProcurementCostsService } from './procurement-costs.service.js'
import { UsersController } from './users.controller.js'
import { UsersService } from './users.service.js'
import { DeviceGrantsController } from './device-grants.controller.js'
import { DeviceGrantsService } from './device-grants.service.js'
import { DeviceGrantLinksService } from './device-grant-links.service.js'
import { UsageGroupsController } from './usage-groups.controller.js'
import { UsageGroupsService } from './usage-groups.service.js'
import { ProjectsController } from './projects.controller.js'
import { ProjectsService } from './projects.service.js'
import { EmployeeKeysController } from './employee-keys.controller.js'
import { EmployeeKeysService } from './employee-keys.service.js'
import { ModelCatalogService } from '../../../packages/gateway-core/src/model-catalog.service.js'
import { GroupBudgetService } from '../../../packages/quota/src/group-budget.service.js'
import { ProjectBudgetService } from '../../../packages/quota/src/project-budget.service.js'
import { ProfileController } from './profile.controller.js'
import { LedGroupsController } from './led-groups.controller.js'
import { LedGroupsService } from './led-groups.service.js'
import { MeProjectsController } from './me-projects.controller.js'
import { MeProjectsService } from './me-projects.service.js'
import { OrgUnitsController } from './org-units.controller.js'
import { OrgUnitsService } from './org-units.service.js'

@Module({
  controllers: [AuthController, ChannelsController, ChannelModelsController, ProcurementCostsController, ModelTestingController, AnalyticsController, ClientController, ModelsController, UsageController, SkillsController, ReportsController, GovernanceController, MonitoringController, MetricsController, OrganizationsController, UsersController, DeviceGrantsController, UsageGroupsController, ProjectsController, EmployeeKeysController, ProfileController, LedGroupsController, MeProjectsController, OrgUnitsController],
  providers: [PrismaService, AuthService, ChannelsService, ChannelModelsService, ProcurementCostsService, ModelBindingService, ModelsService, ModelTestingService, AnalyticsService, UsersService, DeviceGrantLinksService, DeviceGrantsService, AuthGuard, ObjectStorageService, AuditInterceptor, UsageGroupsService, ProjectsService, ModelCatalogService, EmployeeKeysService, GroupBudgetService, ProjectBudgetService, LedGroupsService, MeProjectsService, OrgUnitsService]
})
export class AppModule {}
